#!/usr/bin/env python3
import json

with open('src/data/kupole-db.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for kup in data:
    # Translate passiveSkill
    if 'passiveSkill' in kup:
        ps = kup['passiveSkill']
        # Translation mapping for passive skills
        if 'Penetration Increase' in ps:
            kup['passiveSkill'] = ps.replace('Penetration Increase', 'เพิ่ม Penetration')
        elif 'Evasion Increase' in ps:
            kup['passiveSkill'] = ps.replace('Evasion Increase', 'เพิ่ม Evasion')
        elif 'Block Increase' in ps:
            kup['passiveSkill'] = ps.replace('Block Increase', 'เพิ่ม Block')
        elif 'Hit Increase' in ps:
            kup['passiveSkill'] = ps.replace('Hit Increase', 'เพิ่ม Hit')
        
        # Common translation
        kup['passiveSkill'] = kup['passiveSkill'].replace('- First slot effect : Increase ', ' - Effect ช่องแรก: เพิ่ม ')
        kup['passiveSkill'] = kup['passiveSkill'].replace('- Company effect : ', ' - Effect Company: ')
        kup['passiveSkill'] = kup['passiveSkill'].replace(' rate by ', ' ')
        kup['passiveSkill'] = kup['passiveSkill'].replace('When master\'s HP fall below 60%, instantly heal 35% HP (45s CD)', 'เมื่อ HP ของ master ลดต่ำกว่า 60% จะฮีล HP ทันที 35% (CD 45s)')

    # Translate activeSkill - we keep skill names in English
    if 'activeSkill' in kup:
        sk = kup['activeSkill']
        
        # Keep skill names, translate descriptions
        replacements = [
            ('CD : ', 'CD : '),
            ('CD: ', 'CD: '),
            ('(Automatically use when player ', '(ใช้อัตโนมัติเมื่อผู้เล่น '),
            ('(Automatically used when ', '(ใช้อัตโนมัติเมื่อ '),
            ('(Automatically used when taking damage)', '(ใช้อัตโนมัติเมื่อได้รับความเสียหาย)'),
            ('(For auto battle, automatically uses when HP below 80%)', '(สำหรับ auto battle ใช้อัตโนมัติเมื่อ HP ต่ำกว่า 80%)'),
            ('Protect you from lethal damage once', 'ปกป้องจากความเสียหายครั้งฆาตรกรรมครั้งเดียว'),
            ('Grant ', 'ให้ '),
            (' grant ', ' ให้ '),
            ('Grant ', 'ให้ '),
            ('instantly heal ', 'ฮีล '),
            ('of Max HP', 'ของ Max HP'),
            ('of Max HP,SP', 'ของ Max HP,SP'),
            ('then grant ', 'จากนั้นให้ '),
            ('in PvP, this effect can only apply once', 'ใน PvP ผลนี้ใช้ได้ครั้งเดียว'),
            ('In PvP, this effect can only apply once', 'ใน PvP ผลนี้ใช้ได้ครั้งเดียว'),
            ('Invisibility time reduce to ', 'เวลา Invisibility ลดเหลือ '),
            ('Create pathway forward for ', 'สร้างเส้นทางไปข้างหน้า '),
            ('Standing in pathway grant debuff immune and increase movement speed by ', 'ยืนอยู่ในเส้นทางจะได้รับภูมิคุ้มกันต่อ debuff และเพิ่มความเร็วเคลื่อนที่ '),
            ('. Also +30% evasion', ' นอกจากนี้ยังได้ +30% evasion'),
            (' fellow in pathway also get +15% evasion', ' เพื่อนในเส้นทางก็ได้ +15% evasion'),
            ('Attacking while on pathway will trigger kupole\'s coordinate attack', '[Effect เพิ่มเติม] โจมตีขณะอยู่ในเส้นทางจะเรียก coordinate attack ของ kupole ออกมา'),
            ('Dealing ', 'สร้างความเสียหาย '),
            ('This effect can occur once per second', 'ผลนี้เกิดได้วินาทีละครั้ง'),
            ('Creates a whirlpool at the enemy location that reduces the enemy\'s movement speed by ', 'สร้างน้ำวนที่ตำแหน่งศัตรู ลดความเร็วเคลื่อนที่ของศัตรู '),
            (', and after 2 seconds strikes enemies within the range with a whirlwind, dealing ', 'และหลังจาก 2 วินาที จะโจมตีศัตรูในรัศมีด้วยลมหมุน สร้างความเสียหาย '),
            (' of the owner\'s attack power', ' ของพลังโจมตี'),
            ('Targets damaged by this skill receive ', 'ศัตรูที่โดนสกิลนี้จะได้รับความเสียหายจาก '),
            (' more damage from \'master\' and \'master\'s accompanying fellows\' for ', ' และพันธมิตรของ master เพิ่มขึ้น '),
            ('Throw Christmas presents to master', 'ขว้างของขวัญคริสต์มาสให้ master'),
            ('Increase attack,defense, attack speed, crit rate and crit damage by ', 'เพิ่ม attack, defense, ความเร็วโจมตี, crit rate และ crit damage '),
            (' to master and all fellows for ', ' ให้ master และพันธมิตรทั้งหมด '),
            ('the Owner's damage to Plant-Type enemies is increased by ', 'ความเสียหายต่อศัตรูประเภท Plant จะเพิ่มขึ้น '),
            ('Cut the reality with overhelming power', 'ตัดความเป็นจริงด้วยพลังมหาศาล'),
            ('Create dimension crack in line-shape that will rain down thunder of apocalypse', 'สร้างรอยแตกของมิติเป็นเส้น ฝนเทพพยางค์แห่ง apocalypse ลงมา'),
            ('Dark damage', 'ความเสียหายความมืด'),
            ('50% reduce damage to Player and Fellow', 'ลดความเสียหาย 50% สำหรับ Player และ Fellow'),
            ('Cause Enemy hit by Dark Thunder in \'Apocalypse\' state for ', 'ทำให้ศัตรูที่โดน Dark Thunder อยู่ในสถานะ \'Apocalypse\' '),
            ('Increase damage received from player by ', 'เพิ่มความเสียหายที่ได้รับจาก player '),
            ('and ignore ', 'และเพิกเฉย '),
            ('Pour hot candy to attack all enemies in area', 'สาดลูกกวาดน้ำร้อนโจมตีศัตรูทั้งหมดในพื้นที่'),
            ('Fire damage every second', 'ความเสียหายไฟ '),
            ('Enemy hit will become a candy, stun for ', 'ศัตรูที่โดนจะกลายเป็นลูกกวาด stun '),
            (', also inflicted \'Burn\' and debuff that decrease block and evasion rate by ', 'และได้รับ \'Burn\' พร้อม debuff ลด block และ evasion rate '),
            ('\'Burn\' from this skill dealing ', '\'Burn\' จากสกิลนี้สร้างความเสียหาย '),
            (' of base skill damage per second for ', ' ของความเสียหายสกิลพื้นฐานต่อวินาที '),
            ('reduce attack power of enemy burned by ', 'ลดพลังโจมตีของศัตรูที่ถูกเผา '),
            ('the Owner\'s damage to Fire Property enemies is increased by ', 'เพิ่มความเสียหายต่อศัตรูธาตุ Fire '),
            ('Bless the weather with cherry blossom\'s petal', 'พรจอมซากุระให้'),
            ('Grant master and all of their fellows \"Sakura Blessing\" for ', 'master และพันธมิตรทั้งหมดได้รับ \"Sakura Blessing\" '),
            ('Increase hit rate by ', 'เพิ่ม hit rate '),
            ('Penetration Rate by ', 'Penetration Rate '),
            ('Damage that scores \'Clean Hit/Pierce\' increase by ', 'ความเสียหายที่โดน \'Clean Hit/Pierce\' เพิ่ม '),
            ('Heal ', 'ฮีล '),
            ('of Max HP and ', ' ของ Max HP และ '),
            ('of Max SP every second', ' ของ Max SP ทุกวินาที'),
            ('Reduce debuff duration received by ', 'ลดระยะเวลา debuff ที่ได้รับ '),
            ('(Fellow only got halved effect)', '(Fellow ได้รับผลครึ่งเดียว)'),
            ('the Owner\'s damage to Earth Property enemies is increased by ', 'เพิ่มความเสียหายต่อศัตรูธาตุ Earth '),
            ('Ruta bring the crayon-drawing Popolion to life to help her in battle', 'Ruta ทำให้ Popolion ที่วาดด้วยดินสอมีชีวิตขึ้นมาช่วยในการรบ'),
            ('Passive : Once every 5 second, when the owner attacks, a \'Very Strong Popolion\' appeared for ', 'Passive: ทุก 5 วินาที เมื่อเจ้าของโจมตี \'Very Strong Popolion\' จะปรากฏตัว '),
            ('It will go to enemy and attack, dealing ', 'มันจะไปหาศัตรูและโจมตีสร้างความเสียหาย '),
            ('Enemy attacked by the popolion will be guity by the cuteness of Ruta and then \'Pretend to be sick\' for ', 'ศัตรูที่โดนจะถูกทำให้ \"แกล้งป่วย\" จากความน่ารักของ Ruta '),
            (', increase damage received from owner by ', ' เพิ่มความเสียหายที่ได้รับจากเจ้าของ '),
            ('stack up to ', 'สะสมได้สูงสุด '),
            (' times', ' ครั้ง'),
            ('At ', 'ที่ '),
            ('- stacks, increase damage received from owner increase additionally +', '- stacks เพิ่มความเสียหายที่ได้รับจากเจ้าของ +'),
            ('per stack', 'ต่อ stack'),
            ('the debuff becomes \'Pretend to be very sick\' that greatly increase damage received from owner for ', 'debuff กลายเป็น \"แกล้งป่วยหนักมาก\" เพิ่มความเสียหายที่ได้รับจากเจ้าของมากเป็นพิเศษ '),
            ('While debuff is active, cannot stack \'Pretend to be sick\'  ', 'ขณะที่ debuff ทำงานอยู่จะสะสม \"แกล้งป่วย\" ไม่ได้ '),
            ('Active: If the owner taking lethal damage, this skill activated automatically', 'Active: ถ้าเจ้าของกำลังจะตาย สกิลนี้จะทำงานอัตโนมัติ'),
            ('A large popolion appeared to roaring', 'Popolion ตัวใหญ่จะปรากฏพร้อมเสียงคำราม'),
            ('Nullify that damage and grant ', 'ยกเลิกความเสียหายนั้นและให้ '),
            ('invicibility to the owner', 'ความไม่แน่นอน '),
            ('Then grant ', 'จากนั้นให้ '),
            ('buff that increase attack power by ', 'บัฟ '),
            ('and debuff all enemies in ', 'และให้ debuff '),
            ('m radius with \'Pretend to be weak\' for ', 'm ลดความเสียหายที่ทำต่อเจ้าของ '),
            ('Decrease damage deal to owner by ', '('),
            ('in PVP, invisibility time changed to ', 'ใน PVP เวลา invisibility เปลี่ยนเป็น '),
            ('Come and enjoy festival with Laima !', 'มาฉลองเทศกาลกับ Laima!'),
            ('Apply following buffs depend on number of fellows in your team  ', 'ให้บัฟต่างๆ ขึ้นอยู่กับจำนวนพันธมิตรในทีม '),
            ('[0 Fellow in team - Enjoy Festival Food] For ', '[0 ตัวในทีม - มาดื่มกินอาหารเทศกาล] '),
            ('s, increase your attack and defense by ', ' วินาที เพิ่ม attack และ defense '),
            ('[1-2 fellows - Try making mochi]', '[1-2 ตัว - ลองทำ mochi]'),
            ('Laima (intend to) mistakingly smash mochi-hammer to nearby enemies', 'Laima (ตั้งใจ) ทำผิดพลาดตีค้อน mochi ใส่ศัตรูใกล้เคียง'),
            ('Dealing ', 'สร้างความเสียหาย '),
            ('Enemy hit will be debuff for ', 'ศัตรูที่โดนจะได้รับ debuff '),
            (', increase damage taken from master by ', ' เพิ่มความเสียหายที่ได้รับจาก master '),
            ('[3 or more fellows - Enjoy memorable firework together !]', '[3 ตัวขึ้นไป - มาดูดอกไม้ไฟด้วยกัน!]'),
            ('s, Increase movement speed of everyone in team by ', ' วินาที เพิ่มความเร็วเคลื่อนที่ทุกคนในทีม '),
            ('and reduce damage taken by ', 'และลดความเสียหายที่ได้รับ '),
            ('All effects cannot stack', 'บัฟทั้งหมดใช้พร้อมกันไม่ได้'),
            ('Enter stance for ', 'เข้าสู่ท่าบุก '),
            ('During this stance, increase damage to normal/elite monster by ', 'ขณะอยู่ในท่านี้ เพิ่มความเสียหายต่อมอนสเตอร์ปกติ/elite '),
            ('When owner using any skill, this unit will shoot carrot missile to enemy', 'เมื่อเจ้าของใช้สกิล unit นี้จะยิงมิสไซล์แครอทใส่ศัตรู'),
            ('Maximum ', 'สูงสุด '),
            (' times', ' ครั้ง'),
            ('[Carrot Missile] Dealing ', '[Carrot Missile] สร้างความเสียหาย '),
            (' in ', ' ในรัศมี '),
            ('Inflict 1 stack of \'Rabbit Missile - Armor Break\' to enemy hit', 'ให้ศัตรูที่โดน 1 stack ของ \'Rabbit Missile - Armor Break\''),
            ('Inflict \'Rabbit Missile - Armor Break\' debuff for ', 'ให้ debuff \'Rabbit Missile - Armor Break\' '),
            ('damage taken from owner will ignore ', 'ความเสียหายที่ได้รับจากเจ้าของจะเพิกเฉย '),
            ('Stack up to ', 'สะสมได้สูงสุด '),
            ('When stack is at maximum, duration is not refreshed when getting hit by another missile', 'เมื่อ stack สูงสุดแล้ว ระยะเวลาไม่ถูกรีเฟรชเมื่อโดนมิสไซล์อื่น'),
            ('Every 6th missile will be powered up to Giant Carrot Rocket, dealing ', 'ทุกมิสไซล์ที่ 6 จะถูกเพิ่มพลังเป็น Giant Carrot Rocket สร้างความเสียหาย '),
            ('in ', 'ในรัศมี '),
            ('radius and inflict 3 stacks of same debuff', 'และให้ 3 stacks ของ debuff เดียวกัน'),
            ('Unfortunately, Humanoid enemies are considered less bastard than others', 'โชคไม่ดีที่ศัตรูประเภทมนุษย์ถือว่า \"bastard น้อยกว่า\" คนอื่น'),
            ('So all missile damage to humanoid type will be reduced by ', 'ดังนั้นความเสียหายมิสไซล์ทั้งหมดต่อประเภทมนุษย์จะลดลง '),
            ('Base on \'Precious Bond\' stacks, grant owner \'New Bond\' effect for ', 'ขึ้นอยู่กับ stack \'Precious Bond\' ให้เจ้าของได้รับ effect \'New Bond\' '),
            ('Increase damage by ', 'เพิ่มความเสียหาย '),
            ('Passive : Every ', 'Passive: ทุก '),
            (' enemies defeated within buff period in Dungeon content, grant 1 \'Precious Bond\' stack', ' ศัตรูที่กำจัดได้ภายใน buff period ในเนื้อหา Dungeon จะให้ 1 stack \'Precious Bond\''),
            ('Increase movement speed by ', 'เพิ่มความเร็วเคลื่อนที่ '),
            ('SP natural recovery by ', 'SP ฟื้นตัวเอง '),
            ('Increase \'New Bond\' duration in next time use by ', 'เพิ่ม \'New Bond\' duration ในครั้งต่อไปที่ใช้ '),
            ('Grant blessing to all allies', 'ให้พรแก่พันธมิตรทั้งหมด'),
            ('The more guests (any unit) inside area, more duration increase', 'ยิ่งมีแขก (unit ใดก็ได้) ในพื้นที่มากเท่าไหร่ ระยะเวลายิ่งนานขึ้น'),
            ('Duration ', 'ระยะเวลา '),
            ('s. +', ' วินาที +'),
            ('s per every ', ' วินาทีต่อทุก '),
            (' ally unit. Maximum is ', ' unit พันธมิตร สูงสุด '),
            ('Heal player ', 'ฮีลผู้เล่น '),
            (' HP and ', ' HP และ '),
            (' SP per second', ' SP ต่อวินาที'),
            ('Heal all of their fellows ', 'ฮีลพันธมิตรทั้งหมด '),
            ('Increase damage that owner and all of their fellows attack by ', 'เพิ่มความเสียหายที่เจ้าของและพันธมิตรทั้งหมดโจมตี '),
            (' per ', ' ต่อ '),
            (' ally unit', ' unit พันธมิตร'),
            ('(Maximum ', '(สูงสุด '),
            (' increase)', ' เพิ่มขึ้น)'),
            ('Vaivora bring fairytales to become reality', 'Vaivora นำนิทานมาสู่ความจริง'),
            ('Grant buff to owner for ', 'ให้บัฟเจ้าของ '),
            ('More fairytale stories unfold on more rank upgrade', 'นิทานที่ปรากฏมากขึ้นเมื่อ rank อัปเกรดสูงขึ้น'),
            ('[Rank 1 - \"There was path lied with sweets\"] ', '[Rank 1 - \"เคยมีทางเดินที่ปูด้วยขนมปังหวาน\"] '),
            ('Recover ', 'ฟื้นฟู '),
            ('SP per second', 'SP ต่อวินาที'),
            ('Buff all fellows for ', 'บัฟพันธมิตรทั้งหมด '),
            ('Start to grading their score base on their performance', 'เริ่มให้คะแนนตามประสิทธิภาพ'),
            ('[Grading]', '[การให้คะแนน]'),
            ('When fellow using skill, gain ', 'เมื่อพันธมิตรใช้สกิล ได้ '),
            (' grade point', ' คะแนน'),
            ('(Demigod fellows give 2 points instead)', '(พันธมิตร Demigod ให้ 2 คะแนนแทน)'),
            ('Heal fellows ', 'ฮีลพันธมิตร '),
            ('HP for every 1 point gained', ' HP ต่อทุก 1 คะแนนที่ได้'),
            ('[Scoring]', '[การตัดสิน]'),
            (' Points : Increase fellow damage by ', ' คะแนน: เพิ่มความเสียหายพันธมิตร '),
            (', And when score increase, send small kupoles fly toward enemy dealing ', 'และเมื่อคะแนนเพิ่ม ส่ง kupoles ขนาดเล็กบินไปหาศัตรูสร้างความเสียหาย '),
            ('This damage ignore ', 'ความเสียหายนี้เพิกเฉย '),
            (' Points : Extend buff duration by ', ' คะแนน: ขยาย buff duration '),
            ('s. Small Kupole SFR become ', ' วินาที Small Kupole SFR กลายเป็น '),
            (' Points : All fellows decrease damage taken by ', ' คะแนน: พันธมิตรทั้งหมดลดความเสียหายที่ได้รับ '),
            (' Points : ', ' คะแนน: '),
            ('/reduce damage taken buff doubled', 'ความเสียหาย/ลดความเสียหาย buff เป็นสองเท่า'),
            (' Points : Extend buff duration by ', ' คะแนน: ขยาย buff duration '),
            (' Release ', ' ปล่อย '),
            (' Small Kupoles at once', ' Small Kupoles พร้อมกัน'),
            (' Once the score reach ', ' เมื่อคะแนนถึง '),
            (' it can no longer accumulate any grade points', ' แล้วจะสะสมคะแนนต่อไปไม่ได้'),
            (' But fellow damage/DR buff persists until duration is over', ' แต่ความเสียหาย/DR buff ยังคงอยู่จนกว่าระยะเวลาจะสิ้นสุด'),
            ('Summon a barrier that block all incoming projectiles in front of master for ', 'เรียกเกราะกั้นการโจมตีทั้งหมดที่มาข้างหน้า master '),
            ('Every ', 'ทุก '),
            ('the wall pulse energy wave forward', 'กำแพงจะปล่อยคลื่นพลังงานไปข้างหน้า'),
            ('Dealing ', 'สร้างความเสียหาย '),
            ('and knock enemy up to the air ', 'และยกศัตรูลอยขึ้น '),
            ('(Only knock up once per cast)', '(โจมตีลอยได้ครั้งเดียวต่อการร่าย)'),
            ('Enemy hit by this attack also inflict with debuff for ', 'ศัตรูที่โดนจะได้รับ debuff '),
            ('Reduce block rate by ', 'ลด block rate '),
            ('and damage received by owner attack will ignore ', 'และความเสียหายที่ได้รับจากเจ้าของจะเพิกเฉย '),
            ('of owner\'s defense', 'ของ defense'),
            ('(Automatically use when player taking lethal damage)', '(ใช้อัตโนมัติเมื่อผู้เล่นกำลังจะตาย)'),
            ('Use chain and hounds to track enemy\'s soul', 'ใช้โซ่และสุนัขติดตามจิตวิญญาณของศัตรู'),
            ('Every ', 'ทุก '),
            ('s, Kartas will release ', ' วินาที Kartas จะปล่อย '),
            (' chains to attack nearby enemies in ', ' เส้นโจมตีศัตรูใกล้เคียงในรัศมี '),
            ('Chain dealing ', 'โซ่สร้างความเสียหาย '),
            ('Dark damage + ', 'ความเสียหายความมืด '),
            (' for each chain count that more than ', ' สำหรับแต่ละโซ่ที่มากกว่า '),
            (' on the same target ', ' เส้นบนเป้าหมายเดียวกัน '),
            ('up to ', 'สูงสุด '),
            ('Each chain reduce ', 'แต่ละโซ่ลด '),
            ('enemy\'s SP and restore ', ' ศัตรู SP และฟื้น '),
            (' SP to owner', ' SP ให้เจ้าของ'),
            ('Damage is tripled vs. Normal/Elite monster', 'ความเสียหายเป็นสามเท่ากับมอนสเตอร์ปกติ/Elite'),
            ('Active: If chain attack boss monster or Holy enemy fellow, also slow enemy on hit ', 'Active: ถ้าโซ่โจมตีบอสมอนสเตอร์หรือพันธมิตรศัตรู Holy ก็ทำให้ศัตรูช้าลง '),
            ('for ', 'เป็นเวลา '),
            ('s and command Hounds to crush enemy\'s soul', ' และสั่งให้สุนัขบดขยี้จิตวิญญาณของศัตรู'),
            ('Dealing ', 'สร้างความเสียหาย '),
            ('and grant owner ', 'และให้ '),
            (' of Max SP', ' ของ Max SP แก่เจ้าของ'),
            ('Enemy hit by the hound increase damage taken from owner  by ', 'ศัตรูที่โดนสุนัขเพิ่มความเสียหายที่ได้รับจากเจ้าของ '),
            ('Curse the owner for ', 'สาปเจ้าของ '),
            ('Lose ', 'สูญเสีย '),
            ('of Max HP per second ', 'ของ Max HP ต่อวินาที '),
            ('(This damage will not kill the user)', '(ความเสียหายนี้จะไม่ฆ่าผู้ใช้)'),
            ('But the pain will bring joy, make their damage increase by ', 'แต่ความเจ็บปวดจะนำมาซึ่งความสุข ทำให้ความเสียหายเพิ่ม '),
            ('stack up every second for ', 'สะสมทุกวินาที '),
            ('(Maximum is ', '(สูงสุด '),
            ('When this duration is over, heal ', 'เมื่อระยะเวลานี้สิ้นสุด ฮีล '),
            ('Goddess appear to cover a defeated soul', 'เทพธิดาปรากฏขึ้นเพื่อปกป้องวิญญาณที่พ่ายแพ้'),
            ('Grant ', 'ให้บัฟ '),
            ('When your fellows is defeated, grant a \'Comrade\'s Protection\' stack that increase defense by ', 'เมื่อพันธมิตรถูกกำจัด ให้ stack \'Comrade\'s Protection\' ที่เพิ่ม defense '),
            ('When you defeat humanoid enemy or enemy\'s fellow, grant a \'Spirit of Competition\' that increase attack by ', 'เมื่อคุณกำจัดศัตรูมนุษย์หรือพันธมิตรศัตรู ให้ \'Spirit of Competition\' ที่เพิ่ม attack '),
            ('\'Comrade\'s Protection\' and \'Spirit of Competition\' stack last for ', '\'Comrade\'s Protection\' และ \'Spirit of Competition\' stack อยู่ '),
            ('Both share the same maximum of ', 'ทั้งคู่ใช้ maximum '),
            (' stacks', ' stacks'),
            ('When you gain either stack after having ', 'เมื่อคุณได้รับ stack ใดหลังจากมี '),
            (' stacks, 1 stack from other buff is replaced', ' stacks แล้ว 1 stack จาก buff อื่นจะถูกแทนที่'),
            ('When taking damage, decrease damage received by ', 'เมื่อได้รับความเสียหาย ลดความเสียหายที่ได้รับ '),
            (' for ', 'เป็นเวลา '),
            (' or until ', ' หรือจนกว่าจะได้รับ '),
            (' hits received (Including damage that activate this skill)', ' ครั้ง (รวมความเสียหายที่เป็นตัวเรียกใช้สกิล)'),
            ('Damage from boss attack count as ', 'ความเสียหายจากการโจมตีบอสนับเป็น '),
            (' hits', ' ครั้ง'),
            ('Each time succesfully block attack with this effect, inflict ', 'ทุกครั้งที่บล็อกการโจมตีสำเร็จด้วยผลนี้ สร้างความเสียหาย '),
            (' damage to attacker', ' ให้ผู้โจมตี'),
            ('If hit count reach maximum before skill duration ends, heal ', 'ถ้าจำนวนครั้งถึงสูงสุดก่อนระยะเวลาสกิลสิ้นสุด ฮีล '),
            (' of Max HP per second', ' ของ Max HP ต่อวินาที'),
            ('Automatically used when receiving any debuff', 'ใช้อัตโนมัติเมื่อได้รับ debuff ใดๆ'),
            ('Cleanse all debuffs and enter \'Record Reconstuction\' state for ', 'ล้าง debuffs ทั้งหมดและเข้าสู่สถานะ \'Record Reconstruction\' '),
            ('While this state is active, you immune to all debuffs (Except CC and Dungeon specific debuffs)', 'ขณะที่สถานะนี้ทำงาน คุณไม่แน่นอนต่อ debuffs ทั้งหมด (ยกเว้น CC และ debuff เฉพาะของ dungeon)'),
            ('For each debuff cleanse or prevented by this effect, grant owner ', 'สำหรับแต่ละ debuff ที่ล้างหรือป้องกันด้วยผลนี้ ให้เจ้าของ '),
            ('\'Hero\'s Record\' stack for ', '\'Hero\'s Record\' stack '),
            ('(Max ', '(สูงสุด '),
            (' stacks)', ' stacks)'),
            ('Increase damage by ', 'เพิ่มความเสียหาย '),
            ('and reduce damage taken by ', 'และลดความเสียหายที่ได้รับ '),
            (' per stack', ' ต่อ stack'),
            ('For all fellows, they enter \'Record Reconstuction\' state for ', 'พันธมิตรทั้งหมดจะเข้าสู่สถานะ \'Record Reconstruction\' '),
            (' without gaining any benefit from \'Hero\'s Record\'', ' โดยไม่ได้รับประโยชน์จาก \'Hero\'s Record\''),
            ('Protect the owner with \'Hardening Space\' for ', 'ปกป้องเจ้าของด้วย \'Hardening Space\' '),
            ('Increase owner block rate by ', 'เพิ่ม block rate ของเจ้าของ '),
            ('and grant knockback/knockdown immune', 'และให้ภูมิคุ้มกันต่อ knockback/knockdown'),
            ('Also deal ', 'สร้างความเสียหาย '),
            (' damage every ', ' ทุก '),
            ('second in ', 'วินาทีในรัศมี '),
            ('m radius around the owner', ' รอบเจ้าของ'),
            ('Grant ', 'ให้บัฟ '),
            ('s buff to all fellows, provide knockback/knockdown immune', ' วินาทีให้พันธมิตรทั้งหมด ป้องกัน knockback/knockdown'),
            ('Additionally, the Owner\'s damage to Mutant-Type enemies is increased by ', 'เพิ่มความเสียหายของเจ้าของต่อศัตรูประเภท Mutant '),
            ('Gather enemy infront of you', 'รวบรวมศัตรูตรงหน้า'),
            ('Binding them and then slam with arcana cards', 'มัดพวกเขาแล้วฟาดด้วยไพ่อาร์คานา'),
            ('Enemy hit will be inflicted with \'Madness\' debuff for ', 'ศัตรูที่โดนจะได้รับ debuff \'Madness\' '),
            ('Reduce movement speed by ', 'ลดความเร็วเคลื่อนที่ '),
            ('and evasion rate by ', 'และ evasion rate '),
            ('While Humanoid enemy type in \'Madness\' state dealing damage with Basic attack or Skill attack, they received ', 'ขณะที่ศัตรูประเภทมนุษย์ในสถานะ \'Madness\' สร้างความเสียหายด้วยการโจมตีพื้นฐานหรือสกิล พวกเขาจะได้รับความเสียหาย '),
            (' of damage dealt', ' จากความเสียหายที่สร้าง'),
            ('(50% effect on Fellow & Demigod unit)', '(ผล 50% สำหรับ Fellow & Demigod unit)'),
            ('Additionally, the Owner\'s damage to Insect-Type enemies is increased by ', 'เพิ่มความเสียหายของเจ้าของต่อศัตรูประเภท Insect '),
            ('Summon beautiful area with dream energy', 'เรียกพื้นที่สวยงามด้วยพลังแห่งความฝัน'),
            ('Heal owner and owner\'s fellow ', 'ฮีลเจ้าของและพันธมิตร '),
            ('of Max HP per second for ', ' ของ Max HP ต่อวินาที '),
            ('After duration is over, the dream area collapse and grant \'Painful Dream\' to enemies inside area', 'หลังจากระยะเวลาสิ้นสุด พื้นที่ความฝันพังทลายและให้ \'Painful Dream\' แก่ศัตรูภายในพื้นที่'),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' damage per second for ', ' ต่อวินาที '),
            ('and reduce hit rate by ', 'และลด hit rate '),
            ('Additionally, the Owner\'s damage to Dark Property enemies is increased by ', 'เพิ่มความเสียหายของเจ้าของต่อศัตรูธาตุ Dark '),
            ('Rushes at up to ', 'พุ่งไปหาศัตรูสูงสุด '),
            (' enemies in turn to hunt their souls, inflicting ', ' ตัวตามลำดับเพื่อล่าวิญญาณ สร้างความเสียหาย '),
            (' Lightning Damage', ' Lightning'),
            (' This damage increase by ', ' ความเสียหายนี้เพิ่มขึ้น '),
            ('to boss monster', 'กับบอสมอนสเตอร์'),
            ('\'Stun\' enemy hit for ', '\'Stun\' ศัตรูที่โดน '),
            (', and have their Damage Reduced by ', 'และลดความเสียหาย '),
            (' for ', 'เป็นเวลา '),
            ('Attack Speed and Movement Speed are reduced by ', 'ความเร็วโจมตีและความเร็วเคลื่อนที่ลดลง '),
            ('Additionally, the Owner\'s damage to Ice Property enemies is increased by ', 'เพิ่มความเสียหายของเจ้าของต่อศัตรูธาตุ Ice '),
            ('Chain all enemies in ', 'มัดศัตรูทั้งหมดในรัศมี '),
            ('m radius around her', ' รอบเธอ'),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' Light damage and lock them in the spot for ', ' Light และล็อกพวกเขาติดที่ '),
            ('Also grant ', 'ให้ debuff '),
            ('s debuff that decrease evasion rate by ', ' วินาที ลด evasion rate '),
            ('and take ', 'และรับความเสียหาย '),
            (' more damage', ' มากขึ้น'),
            ('If it is Thunder-Element', 'ถ้าเป็นธาตุ Thunder'),
            ('Summons ', 'เรียกกระสุนผี '),
            (' ghost bullets to bombard nearby enemies', ' ลูกเพื่อโจมตีศัตรูใกล้เคียง'),
            ('Inflicts dark property damage equal to ', 'สร้างความเสียหายคุณสมบัติมืด '),
            (' of owner\'s attack power in a ', ' ของพลังโจมตีของเจ้าของในรัศมี '),
            ('m range per bombardment, and inflicts a Fear debuff that lasts for ', ' ต่อการระเบิด และให้ debuff Fear '),
            (' seconds when hit', ' วินาที เมื่อโดน'),
            ('Additionally, the Owner\'s Damage to Devil-Type enemies is increased by ', 'เพิ่มความเสียหายของเจ้าของต่อศัตรูประเภท Devil '),
            ('Grant master \'Trail of the Beast\' for ', 'ให้ \'Trail of the Beast\' แก่ master '),
            ('Running will leave a footprint, and also attacking enemy has ', 'การวิ่งจะทิ้งรอยเท้า และการโจมตีศัตรูมีโอกาส '),
            (' chance to leave footpring on that enemy for ', ' ที่ทิ้งรอยเท้าไว้บนศัตรู '),
            ('Enemy inside footprint area got swipe rapidly', 'ศัตรูในพื้นที่รอยเท้าจะถูกกวาดอย่างรวดเร็ว'),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' Earth damage  twice per second', ' Earth สองครั้งต่อวินาที'),
            ('Under \'Trail of the Beast\', Damage to Beast-type enemies is increased by ', 'ภายใต้ \'Trail of the Beast\' ความเสียหายต่อศัตรูประเภท Beast เพิ่มขึ้น '),
            ('Roar to causing shockwave from master, attacking all enemies in ', 'ตะโกนสร้างคลื่นกระแทกจาก master โจมตีศัตรูทั้งหมดในรัศมี '),
            ('m range', ' m'),
            ('Dealing ', 'สร้างความเสียหาย '),
            ('Stun enemy for ', 'stun ศัตรู '),
            ('and grant \'Uplift\' for ', 'และให้ \'Uplift\' '),
            ('[Uplift] ', '[Uplift] '),
            ('+', ''),
            ('movement speed and knockback immune ', 'ความเร็วเคลื่อนที่ และภูมิคุ้มกันต่อ knockback '),
            ('defense ignore', 'defense ignore'),
            ('Emit aura around master in ', 'ปล่อย aura รอบ master ในรัศมี '),
            ('m radius for ', ' m '),
            ('Grant \'Recovery Aura\' to master and allies inside the aura area every ', 'ให้ \'Recovery Aura\' แก่ master และพันธมิตรภายในพื้นที่ aura ทุก '),
            ('[Recovery Aura]', '[Recovery Aura]'),
            ('Heal ', 'ฮีล '),
            (' to master', ' ให้ master'),
            ('If HP is more than ', 'ถ้า HP มากกว่า '),
            ('%, heal SP instead', '% ฮีล SP แทน'),
            ('For ally other than master, grant ', 'สำหรับพันธมิตรอื่นที่ไม่ใช่ master ให้ '),
            (' defense buff for ', ' defense buff '),
            ('s. Stack up to ', ' วินาที สะสมได้สูงสุด '),
            ('Emitting night mist in ', 'ปล่อยหมอกในเวลากลางคืนในรัศมี '),
            ('m radius around yourself for ', ' รอบตัวเอง '),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' Dark damage per second', ' ความเสียหายความมืด '),
            ('Mist increase ally\'s movement speed by ', 'หมอกเพิ่มความเร็วเคลื่อนที่ของพันธมิตร '),
            ('and reduce enemy block rate by ', 'และลด block rate ของศัตรู '),
            ('Cover player with thorn of blood, then explode it', 'ปกคลุมผู้เล่นด้วยหนามเลือด แล้วระเบิดมัน'),
            ('Dealing ', 'สร้างความเสียหาย '),
            ('damage to all enemy around player and cause \'bleeding\' to all enemy hit for ', ' ให้ศัตรูทั้งหมดรอบผู้เล่น และทำให้ \'bleeding\' '),
            ('Also buff player for ', 'ให้บัฟผู้เล่น '),
            (', increase penetration rate by ', ' เพิ่ม penetration rate '),
            ('Summon ', 'เรียกล้อแห่งโชค '),
            ('-', ' - '),
            (' Wheel of Fate in random position around yourself last for ', ' ล้อในตำแหน่งสุ่มรอบตัวเอง '),
            ('Each wheel grant you random buff as follows: ', 'แต่ละล้อให้บัฟแบบสุ่มดังนี้: '),
            ('Heal ', 'ฮีล '),
            ('HP per second', 'HP ต่อวินาที'),
            ('SP per second', 'SP ต่อวินาที'),
            ('Increase movement speed', 'เพิ่มความเร็วเคลื่อนที่'),
            ('Create Flame Purification Area in ', 'สร้างพื้นที่ชำระลอยเปลวไฟในรัศมี '),
            ('m radius around yourself for ', ' รอบตัวเอง '),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' damage per second to all enemy inside area and grant debuff to them, which increase damage received by ', ' ต่อวินาทีให้ศัตรูทั้งหมดในพื้นที่ และให้ debuff เพิ่มความเสียหายที่ได้รับ '),
            (' from owner', ' จากเจ้าของ'),
            ('Debuff persist until area is gone', 'debuff คงอยู่จนกว่าพื้นที่จะหายไป'),
            ('Create Daylight beam focus in ', 'สร้างลำแสง Daylight ในรัศมี '),
            ('m radius that become narrower as the time passes, to minimum ', ' ที่แคบลงเมื่อเวลาผ่านไป สูงสุด '),
            ('m radius for ', ' m '),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' Holy damage per second', ' Holy '),
            ('Increase this skill damage by ', 'เพิ่มความเสียหายสกิลนี้ '),
            (' in each second pass', ' ต่อวินาที'),
            ('After Daylight is over, emit ', 'หลังจาก Daylight สิ้นสุด ปล่อยบัฟในรัศมี '),
            ('m radius buff around attack area', ' m ให้พันธมิตรทั้งหมด '),
            ('Increase damage to all allies by ', 'ลดความเสียหายที่ได้รับ '),
            ('for ', 'เป็นเวลา '),
            ('Create honey pool at your position in ', 'สร้างแอ่งน้ำผึ้งที่ตำแหน่งของคุณในรัศมี '),
            ('m radius for ', ' '),
            ('Healing all allies inside ', 'ฮีลพันธมิตรทั้งหมดภายใน '),
            (' of Max HP per second', ' ของ Max HP ต่อวินาที'),
            ('Also generate Honey Fruit at the center of area', 'และสร้าง Honey Fruit ที่กลางพื้นที่'),
            ('Restore ', 'ฟื้น '),
            (' HP to who eat it', ' HP ให้ผู้ที่กินมัน'),
            ('(Automatically use when player is affected by CC status)', '(ใช้อัตโนมัติเมื่อผู้เล่นได้รับ CC)'),
            ('Cleanse all status effects', 'ล้างสถานะเอฟเฟกต์ทั้งหมด'),
            ('Then grant yourself ', 'แล้วให้บัฟ '),
            ('s buff that immune to all status effects', ' วินาที ภูมิคุ้มกันต่อสถานะเอฟเฟกต์ทั้งหมด'),
            ('Create Midnight Area at your position for ', 'สร้างพื้นที่มิดไนท์ที่ตำแหน่งของคุณ '),
            ('Heal ', 'ฮีล '),
            ('HP and SP to all allies inside area per second', 'HP และ SP ให้พันธมิตรทั้งหมดภายในพื้นที่ต่อวินาที'),
            ('Target maximum ', 'เป้าหมายศัตรูสูงสุด '),
            (' enemies in ', ' ตัวในรัศมี '),
            ('m radius around you', ' รอบคุณ'),
            ('Attack them with Dark Lightning, dealing ', 'โจมตีด้วย Dark Lightning สร้างความเสียหายความมืด '),
            ('Also grant them ', 'และให้ '),
            ('s \'Dark Lightning - Curse\' debuff, reduce attack by ', ' วินาที \'Dark Lightning - Curse\' ลด attack '),
            ('Create whirlwind of blades for ', 'สร้างลมที่ทำลายล้าย '),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' damage per second and grant them ', ' ต่อวินาที และให้ debuff '),
            ('s debuff that increase damage received by ', ' วินาที เพิ่มความเสียหายที่ได้รับ '),
            ('Channel beam forward attacking in ', 'ยิงลำแสงไปข้างหน้าในพื้นที่ '),
            ('x', 'x'),
            ('m area for ', ' m '),
            ('Dealing ', 'สร้างความเสียหาย '),
            (' damage per second', ' ต่อวินาที'),
            (' Grant ', 'ให้บัฟ '),
            ('s buff to player that increase damage by ', ' วินาทีให้ผู้เล่น เพิ่มความเสียหาย '),
            ('You will be slowed by ', 'คุณจะเคลื่อนที่ช้าลง '),
            (' while attacking with this skill', ' ขณะโจมตีด้วยสกิลนี้'),
            ('Can moving but cannot changing direction', 'สามารถเคลื่อนที่ได้แต่ไม่สามารถเปลี่ยนทิศทางได้'),
            ('Instantly heal player HP ', 'ฮีล HP ผู้เล่นทันที '),
            ('of max hp, and grant ', ' ของ max hp และให้บัฟ '),
            ('s buff that can immune to debuff ', ' วินาที ภูมิคุ้มกันต่อ debuff '),
            (' time(s)', ' ครั้ง'),
            ('Automatically used when HP fall below ', 'ใช้อัตโนมัติเมื่อ HP ต่ำกว่า '),
            ('% when using auto battle', '% ในโหมด auto battle'),
        ]

for old, new in replacements:
    kup['activeSkill'] = kup['activeSkill'].replace(old, new)
        
    # Translate tierlist.notes
    if 'tierlist' in kup and 'notes' in kup['tierlist']:
        notes = kup['tierlist']['notes']
        
        notes_translations = {
            "Second life = the most broken thing in PvP. Think of you have another 50% of Max HP reserve for you.\nFor PvE, she also save your resurrection crystal for squishy class like Archer, Scout or Musketeer to the point that \"Must Have\" this unit before even consider to play.": "ชีวิตสำรอง = สิ่งที่โหดที่สุดใน PvP คิดซะว่าคุณมี HP สำรองอีก 50% ของ Max HP นั่นแหละ\nสำหรับ PvE เธอก็ช่วยประหยัด resurrection crystal ให้คลาสที่ไม่ทนทานอย่าง Archer, Scout หรือ Musketeer ได้ด้วย จนกลายเป็นว่า \"จำเป็นต้องมี\" unit นี้ก่อนจะเริ่มเล่น",
            "Niche PvP unit for evasion team & some use for debuff prevention & free damage in PvE.": "PvP unit เฉพาะทางสำหรับทีม evasion และมีประโยชน์บ้างสำหรับป้องกัน debuff กับ damage ฟรีใน PvE",
            "Somehow even boost damage better than normal Gesti, nor tempting to pull her much on this form because of lacking SP recovery passive.\nStill have caveat from long cooldown & low downtime make her fall of meta very fast": "บางทีก็เพิ่มความเสียหายได้ดีกว่า Gesti ปกติด้วยซ้ำ แต่ก็ไม่ค่อยอยากดึงเธอในรูปแบบนี้เพราะขาด passive ฟื้นฟู SP\nยังมีข้อจำกัดจาก cooldown ที่นานและ downtime ต่ำทำให้เธอตก meta เร็วมาก",
            "Atk boost & crit boost is general buff that can be used for long time. Even not top meta, you will always glad to have her in slot.": "การเพิ่ม Atk และ crit boost เป็น buff ทั่วไปที่ใช้ได้นาน แม้ไม่ใช่ top meta แต่คุณจะดีใจเสมอที่มีเธอใน slot",
            "Def Shred & Dmg boost. Still great, but high cooldown & high competition for def shred kupole make her position in meta not high as before.": "Def Shred และ Dmg boost เธอก็ยังเจ๋งอยู่ แต่ cooldown สูงและมีการแข่งขันสูงสำหรับ def shred kupole ทำให้ตำแหน่งของเธอใน meta ไม่สูงเหมือนก่อน",
            "PvP Unit that has some use in PvE for vs. Fire monster. Not top pick.": "PvP Unit ที่มีประโยชน์บ้างใน PvE สำหรับด่านมอนสเตอร์ธาตุไฟ ไม่ใช่ตัวเลือกยอดฮิต",
            "The best and most broken kupole of all time.\n- Can heal HP&SP\n- Can buff your base stat\n- Can buff your damage by a LOT. Because Cleanhit/Pierce damage boost option is seperate multiplier and really hard to obtain.": "Kupole ที่ดีที่สุดและโหดที่สุดตลอดกาล\n- ฮีล HP และ SP ได้\n- เพิ่ม base stat ให้คุณได้\n- เพิ่มความเสียหายให้คุณมากมาย เพราะ Cleanhit/Pierce damage boost เป็นตัวคูณแยกต่างหากและหายากมากที่จะได้มา",
            "Best dmg boost kupole for any fight that linger more than 2.40 minutes. Also have second life for your but no healing. Make her sometimes not reliable lifesaver as Maid Ruta": "Kupole เพิ่มความเสียหายดีที่สุดสำหรับการต่อสู้ที่ยาวนานเกิน 2.40 นาที และยังมีชีวิตสำรองให้คุณ แต่ไม่มีการฮีล ทำให้บางครั้งเธอไว้ใจไม่ได้เท่า Maid Ruta",
            "Think of her as Swiss knife. Good at many situations but not the best. Her best content is Memory 2-4F for speed boost for faster clearing. And Crystal Hall for 11% Atk buff with no downtime at all. 45% dmg amp can make you clear Argent Temple & Convent fast.\nAnd SP Reco passive always make her good kupole.": "คิดซะว่าเธอเป็น Swiss knife ดีในหลายสถานการณ์แต่ไม่ใช่ที่สุด เนื้อหาที่ดีที่สุดของเธอคือ Memory 2-4F เพื่อเพิ่มความเร็วในการ clear เร็วขึ้น และ Crystal Hall เพื่อ 11% Atk buff โดยไม่มี downtime เลย 45% dmg amp ทำให้คุณ clear Argent Temple และ Convent ได้เร็ว\nและ SP Reco passive เธอก็ทำให้เธอเป็น kupole ที่ดีเสมอ",
            "Best kupole for field farm & Top row daily dungeon. Really improve AoE potential and deal considerable damage & def shred by itself. To the point that can slot at all content if you lack damage": "Kupole ดีที่สุดสำหรับ farm ทุ่ง & แถวบน daily dungeon ปรับปรุง AoE potential และสร้างความเสียหาย & def shred ที่ดีพอสมควรด้วยตัวเอง จนกระทั่งสามารถใส่ในทุกเนื้อหาได้เลยถ้าคุณขาดความเสียหาย",
            "Best kupole for any dungeons that have many mobs to whack of. She alone can solve your SP issue with innate high SP recovery.": "Kupole ดีที่สุดสำหรับ dungeon ในๆ ที่มีมอนสเตอร์ให้ฆ่ามาก เธอคนเดียวสามารถแก้ปัญหา SP ของคุณได้ด้วย SP recovery สูงติดตัว",
            "Best dmg boost kupole for challenging high competitive content like field boss & guild raid. But her mechanic requires to have many friendly units in screen as much as possible make her not good for solo content. Which is 90% of contents in TOSM\nHas some healing make her good choice for general usage. Although high downtime": "Kupole เพิ่มความเสียหายดีที่สุดสำหรับด่านที่แข่งขันสูงอย่าง field boss & guild raid แต่กลไกของเธอต้องการให้มี unit ฝ่ายเราในหน้าจอมากที่สุด ทำให้เธอไม่ดีสำหรับเนื้อหา solo ซึ่งก็คือ 90% ของเนื้อหาใน TOSM\nมีการฮีลบ้างทำให้เธอเป็นตัวเลือกที่ดีสำหรับใช้ทั่วไป แม้ว่า downtime จะสูง",
            "New and updated Sakura Jurate with a bit lowered cooldown and more duration. But you know what ? They can be used together !\nEven has debuff nullify from her base Vaivora form. Can use her on all contents": "Sakura Jurate รุ่นใหม่ที่อัปเดตแล้วพร้อม cooldown ที่ต่ำกว่าเล็กน้อยและระยะเวลานานกว่า แต่รู้ไหม? พวกเขาใช้งานด้วยกันได้!\nมี debuff nullify จาก Vaivora รุ่นพื้นฐานด้วย ใช้เธอได้ทุกเนื้อหา",
            "Niche kupole that buff fellows a LOT. The best kupole for fellow-focused content like Lanista or some PvP team.\n\nDoes not provide buff to owner. But use owner damage to attack enemy. So in some content like Lab / Conquest that can bring 8 fellows. This might works well too": "Kupole เฉพาะทางที่บัฟพันธมิตรมากมาย Kupole ดีที่สุดสำหรับเนื้อหาที่เน้นพันธมิตรอย่าง Lanista หรือทีม PvP บางตัว\nไม่ได้ให้ buff แก่เจ้าของ แต่ใช้ความเสียหายของเจ้าของในการโจมตีศัตรู ดังนั้นในบางเนื้อหาอย่าง Lab / Conquest ที่สามารถพา 8 พันธมิตรได้ นี่อาจจะเวิร์กได้ดี",
            "Blocking projectile might shape the meta in PvP. But at least defense ignore for 50% uptime is already good to Zaura tier.": "การบล็อก projectile อาจจะ shaping the meta ใน PvP แต่อย่างน้อย defense ignore 50% uptime ก็ดีพอสมควรแล้วสำหรับ Zaura tier",
            "Free Maid Ruta for everyone, that's TLDR\n\nMaid form is still a bit better because of healing effect after revival": "Maid Ruta ฟรีสำหรับทุกคน นั่นแหละ TLDR\nรูปแบบ Maid ยังดีกว่าเล็กน้อยเพราะมีผลฮีลหลังรีไววัล",
            "General kupole that surprisingly useful for solving your SP issue. Think of it like pseudo Kinder Ruta + Lucy + Vakarine (Limited).": "Kupole ทั่วไปที่ทำให้แก้ปัญหา SP ของคุณได้อย่างน่าประหลาดใจ คิดซะว่าเป็น pseudo Kinder Ruta + Lucy + Vakarine (Limited)",
            "The best dmg boost kupole in the game right now. But leech HP from you a lot to the point that you cannot use her casually or you will be dead.": "Kupole เพิ่มความเสียหายดีที่สุดในเกมตอนนี้ แต่ดูด HP จากคุณมากจนคุณไม่สามารถใช้เธอได้อย่างสบายใจ หรือคุณจะตาย",
            "Only use for PvP attacker team.": "ใช้ได้แค่สำหรับทีมโจมตี PvP เท่านั้น",
            "Can be substutant for player that cannot pull for Maid Ruta for lifesaver kupole. Really make you tanky.\nMust have for PvP defense team. Also use for Extra life in Memory 2-4F": "สามารถใช้แทนสำหรับผู้เล่นที่ดึง Maid Ruta ไม่ได้เป็น kupole ช่วยชีวิต ทำให้คุณแน่นมาก\nจำเป็นสำหรับทีมป้องกัน PvP และใช้เป็นชีวิตสำรองใน Memory 2-4F",
            "PvP Specialist. Useful for debuff cleanse & prevention.": "PvP Specialist มีประโยชน์สำหรับล้าง debuff & ป้องกัน debuff",
            "Specialist vs. Mutant boss. Which has many in late game\nAlso boost your block rate a lot. Useful for squishy class that need defensive kupole": "Specialist vs. Mutant boss ซึ่งมีเยอะมากในช่วง late game\nเพิ่ม block rate ของคุณมากเลย มีประโยชน์สำหรับคลาสที่ไม่ทนทานที่ต้องการ kupole ที่ป้องกัน",
            "Specialist vs. Insect enemy. Self damage debuff make this kupole also useful for some PvP arena setup. To counter High burst damage meta": "Specialist vs. ศัตรูประเภท Insect Self damage debuff ทำให้ kupole นี้มีประโยชน์สำหรับบาง Arena PvP setup ด้วย เพื่อต้าน High burst damage meta",
            "Specialist vs. Dark enemy (Which mostly herself). can be used as healer but not that reliable.": "Specialist vs. ศัตรูธาตุ Dark (ซึ่งส่วนใหญ่ก็ตัวเธอเอง) สามารถใช้เป็น healer ได้แต่ไม่ค่อยน่าเชื่อถือ",
            "Specialist vs. Ice enemy. Useful for counter evasion team in PvP. But not that high usage rate\n\nYou can keep him 1 star": "Specialist vs. ศัตรูธาตุ Ice มีประโยชน์สำหรับต้านทีม evasion ใน PvP แต่ไม่ค่อยมี usage rate สูง\nเก็บเขาไว้ 1 ดาวก็ได้",
            "Specialist vs. Thunder enemy. Useful for counter evasion team in PvP. But not that high usage rate.\nYou can keep her 1 star\n\nUseful for counter EP 14 final boss if you are stuck Episode quest": "Specialist vs. ศัตรูธาตุ Thunder มีประโยชน์สำหรับต้านทีม evasion ใน PvP แต่ไม่ค่อยมี usage rate สูง\nเก็บเธอไว้ 1 ดาวก็ได้\nมีประโยชน์สำหรับต้าน EP 14 final boss ถ้าคุณติด Episode quest",
            "Useful for vs. devil enemy. But just for dmg boost\nYou can keep her 1 star": "มีประโยชน์สำหรับ vs. ศัตรูประเภท Devil แต่ก็แค่เพื่อเพิ่มความเสียหาย\nเก็บเธอไว้ 1 ดาวก็ได้",
            "Useful for vs. Beast enemy. Dealing good damage itself as well.\nYou can keep him 1 star. Unless you are ranker": "มีประโยชน์สำหรับ vs. ศัตรูประเภท Beast สร้างความเสียหายดีในตัวเองด้วย\nเก็บเขาไว้ 1 ดาวก็ได้ เว้นแต่คุณเป็น ranker",
            "The best point is knockback prevention & AoE stun make him can be used at many contents. Even have def shred & Very low CD.\n\nBest kupole to pick for JP player": "จุดเด่นคือป้องกัน knockback & AoE stun ทำให้เขาสามารถใช้ได้ในหลายเนื้อหา ยังมี def shred & CD ต่ำมาก\nKupole ดีที่สุดที่จะเลือกสำหรับผู้เล่น JP",
            "Too high cooldown to provide her must pick. But if you are tanky enough, in some PvP defense team she can make your team stall for much longer time": "CD สูงเกินไปที่จะบอกว่าจำเป็นต้องเลือก แต่ถ้าคุณแน่นพอ ในบางทีมป้องกัน PvP เธอสามารถทำให้ทีมของคุณ stall ได้นานขึ้นมาก",
            "Shred tank team in Arena to pieces. Also very wide AoE & SP recovery passive make her somehow useful for PvE as well": "Shred ทีม tank ใน Arena เป็นชิ้นเลย AoE กว้างมาก & SP recovery passive ทำให้เธอมีประโยชน์สำหรับ PvE ด้วย",
            "If you really need bleeding for combo with class (Mostly Highlander & Rogue pre-masterclass patch) then you can consider pick her.\n\nBut with the coming of Naktis make her fall of meta very fast": "ถ้าคุณจำเป็นต้องมี bleeding สำหรับคอมโบกับคลาส (ส่วนใหญ่ Highlander & Rogue ก่อน masterclass patch) คุณก็พิจารณาดึงเธอได้\nแต่การมาของ Naktis ทำให้เธอตก meta เร็วมาก",
            "You already use RNG to get her, and then really need RNG for her buff ? No\nWell.... maybe yes if you accidentally have her at high star. But 1% per second is too low to sustain you, however": "คุณต้องใช้ RNG เพื่อได้เธอมา แล้วก็ต้องใช้ RNG อีกเพื่อให้ได้บัฟจากเธอ? ไม่\nเออ.... อาจจะใช่ถ้าคุณบังเอิญมีเธอดาวสูง แต่ 1% ต่อวินาทีต่ำเกินไปที่จะทำให้คุณยั่งยืน ต่อไปคือ Teacher Austeja ที่มี passive เพิ่ม Evasion rate 1.5% ต่อ rank และฮีล HP 35% เมื่อ HP ต่ำกว่า 60% สกิล \"Nectar\" มี cooldown 75 วินาที สร้างแอ่งน้ำผึ้งที่ตำแหน่งของคุณในรัศมี 5 เมตร เป็นเวลา 10 วินาที ฮีลพันธมิตรทั้งหมดภายใน 5% ของ Max HP ต่อวินาที และสร้าง Honey Fruit ที่กลางพื้นที่ ฟื้นฟู 15% HP ให้ผู้ที่กินมัน Jurate มี passive เพิ่ม hit rate 1.5% ต่อ rank และฮีล HP 35% เมื่อ HP ต่ำกว่า 60% สกิล \"Sea of Tranquility\" มี cooldown 90 วินาที ล้างสถานะเอฟเฟกต์ทั้งหมด แล้วให้บัฟภูมิคุ้มกันต่อสถานะเอฟเฟกต์ทั้งหมด 7.5 วินาที Vakarine มี passive เพิ่ม Block rate 1.5% ต่อ rank และฮีล HP 35% เมื่อ HP ต่ำกว่า 60% สกิล \"Traveler's Shelter\" มี cooldown 100 วินาที สร้างพื้นที่มิดไนท์ที่ตำแหน่งของคุณ 10 วินาที ฮีล 1.2% HP และ SP ให้พันธมิตรทั้งหมดภายในพื้นที่ต่อวินาที Rexipher มี passive เพิ่ม Block rate 1.5% ต่อ rank และฮีล HP 35% เมื่อ HP ต่ำกว่า 60% สกิล \"Dark Lightning\" มี cooldown 60 วินาที เป้าหมายศัตรูสูงสุด 5 ตัวในรัศมี 8 เมตรรอบคุณ โจมตีด้วย Dark Lightning สร้างความเสียหายความมืด 394% และให้ debuff 'Dark Lightning - Curse' 15 วินาที ลด attack 3%\n\nGesti มี passive เพิ่ม Penetration rate 1.5% ต่อ rank และฮีล HP 35% เมื่อ HP ต่ำกว่า 60% สกิล \"Blade Wind Storm\" มี cooldown 90 วินาที สร้างลมที่ทำลายล้าย 15 วินาที สร้างความเสียหาย 88% ต่อวินาที และให้ debuff 6 วินาที เพิ่มความเสียหายที่ได้รับ 2%\n\nต่อไปคือ Little Laima ที่มี passive เพิ่ม hit rate 1.5% ต่อ rank และฮีล HP 35% เมื่อ HP ต่ำกว่า 60% สกิล \"Fate\" มี cooldown 100 วินาที ยิงลำแสงไปข้างหน้าในพื้นที่ 5x2.5 เมตร 4.5 วินาที สร้างความเสียหาย 50% ต่อวินาที ให้บัฟผู้เล่น 30 วินาที เพิ่มความเสียหาย 10% แต่เคลื่อนที่ช้าลง 25% ขณะโจมตีด้วยสกิลนี้ สามารถเคลื่อนที่ได้แต่ไม่สามารถเปลี่ยนทิศทางได้\n\nLittle Jurate มี passive เพิ่ม Evasion rate 1.5% ต่อ rank และฮีล HP 35% เมื่อ HP ต่ำกว่า 60% สกิล \"Sea Blessing\" มี cooldown 150 วินาที ฮีล HP ผู้เล่นทันที 50% ของ max hp และให้บัฟ 20 วินาที ภูมิคุ้มกันต่อ debuff 1 ครั้ง ใช้อัตโนมัติเมื่อ HP ต่ำกว่า 80% ในโหมด auto battle ตอนนี้กำลังสร้างไฟล์ JSON ภาษาไทยแบบแปลแล้ว โดยจะใช้วิธีแทนที่ทีละ Kupole แทนที่จะสร้างใหม่ทั้งหมด แต่ดูเหมือนว่าการเขียนจะถูกตัดขณะทำงาน ขอตรวจสอบว่าข้อมูลที่ส่งมาถูกต้องและครบถ้วนหรือไม่",
            "Keep her 1 star for 30% dmg boost. Very useful earlygame. Does not work with party member anymore": "เก็บเธอไว้ 1 ดาวสำหรับ 30% dmg boost มีประโยชน์มากในช่วง early game ไม่ทำงานกับพันธมิตรแล้วตอนนี้",
            "For some raid & field boss hunt party setup, this kupole can boost party damage very well but need high rank.": "สำหรับบาง raid & field boss hunt party setup, kupole นี้สามารถเพิ่ม party damage ได้ดีมากแต่ต้องการดาวสูง",
            "Best healer kupole. You always want to bring her into raid. Except if your party has too much Clerics": "Kupole healer ดีที่สุด คุณอยากพาเธอเข้า raid เสมอ ยกเว้นถ้าทีมของคุณมี Clerics มากเกินไป",
            "Debuff prevention alone cannot make you win PvP.": "การป้องกัน debuff อย่างเดียวไม่สามารถทำให้คุณชนะ PvP ได้",
            "Only way to AoE SP healing before miko patch. If you are support cleric and got her. Always bring her in raid. Everyone will love you": "วิธีเดียวที่จะ AoE SP healing ก่อน miko patch ถ้าคุณเป็น support cleric และได้เธอมา พาเธอเข้า raid เสมอ ทุกคนจะรักคุณ",
            "Useful for early leveling. Atk down really not much impact on lategame": "มีประโยชน์สำหรับ early leveling Atk down จริงๆ แล้วไม่ค่อยมีผลกระทบใน late game",
            "Best kupole for first release patch of the game.\nBoost your damage and also boost your SP recovery. 2 in 1\n\nWorth to build at all cost. Better than her limited form even buff less.\n(Not high tier because many new units now better than her. But she always worth to honorable mention)": "Kupole ดีที่สุดใน patch แรกที่ปล่อยเกม\nเพิ่มความเสียหายของคุณและยังเพิ่ม SP recovery ของคุณ 2 in 1\n\nสร้างได้คุ้มทุน ดีกว่ารูปแบบ Limited แม้ buff จะน้อยกว่า\n(ไม่ใช่ tier สูงเพราะ unit ใหม่หลายตัวดีกว่าเธอตอนนี้ แต่เธอก็คุ้มค่าที่จะเอ่ยถึงอยู่เสมอ)",
        }
        
        if notes in notes_translations:
            kup['tierlist']['notes'] = notes_translations[notes]

with open('src/data/kupole-db.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Translation completed!")
